spring:
  datasource:
    username: "postgres"
    password: "qwerty"
    url: "jdbc:postgresql://localhost:5432/mother-and-newbornbabes"
    driver-class: "org.postgresql.Driver"
  jpa:
    show-sql: true
